### ISSUE TITLE
Homepage

### ISSUE THREAD

**Issue by katiihnat** [Kandroodi/IberianSaints#25]
Hi Mojtaba,

Could you possibly change the text on the homepage? 

It should read:

Iberian Saints

Saints were the heroes of medieval culture and the centre of lively cults which presented them as active intercessors and examples for their fellow Christians. This principle applies for all of medieval Europe, but how saints were venerated in medieval Iberia is less well-known, whether they were considered martyrs and were thought to have died for the faith, or confessors and had suffered willingly in life, often through ascetic practices. The Iberian saints database combines liturgical, musical and material evidence enabling for the first time a holistic exploration of saints’ cults in medieval Iberia. It integrates liturgical texts found in manuscripts with the material culture that made up saints’ cults, including churches, relics, religious objects, inscriptions and the evidence from charters. Visualized on maps, this information opens up new understandings of how devotion to saints emerged in Iberia, how it moved and changed over time, and the forms it took in different areas. It integrates two projects: the AHRC-funded ‘Doctrine, devotion and cultural expression in the cults of medieval Iberian saints’ (hosted at the University of Bristol) and the NWO-funded ‘Making a martyr in medieval Iberia, 589-1080’ (hosted at the Radboud Universiteit Nijmegen), and has been put together by a team that includes Catherine Hoijinck, Emma Hornby, Kati Ihnat, Maeve O’Donnell and Jamie Wood, as well as the Humanities Lab at the Radboud University Nijmegen.

**Comment by Kandroodi** [comment]
It is done.
