### ISSUE TITLE
For all categories - external links

### ISSUE THREAD

**Issue by katiihnat** [Kandroodi/IberianSaints#28]
Can there be more than one 'external link'?

**Comment by Kandroodi** [comment]
We discussed this before, there are two ways to implement multiple inputs for external links:
1) having a text box input (like what we have now) and import the links separated with an e.g. ";". This will make the data retrieval complex.
2) Like what we had in the initial implementation, I can create a separate form for external links and the user can select multiple of the links in the field.

**Comment by Kandroodi** [comment]
It is done.
