### ISSUE TITLE
Location

### ISSUE THREAD

**Issue by katiihnat** [Kandroodi/IberianSaints#29]
Mojtaba - we have a bit of a dilemma - we need to find a way to associate liturgical manuscripts, objects and inscriptions to locations that are not only churches. We don't know how to organize this in the database. Sometimes liturgical manuscripts, objects and inscriptions are in a city or a region, and are not all attached to a church --> the question is how to introduce 'city' or 'region' as a category 

Would it be possible to talk about this? This is an important feature for us. Thanks!

**Comment by Kandroodi** [comment]
See #33 #23 #24

**Comment by Kandroodi** [comment]
It is done.
