### ISSUE TITLE
Saints

### ISSUE THREAD

**Issue by katiihnat** [Kandroodi/IberianSaints#31]
Is it possible to have multiple languages available for the entry of saints' names? English, Spanish, Latin

OR for searching - would it be possible to have a drop-down menu for saints' names, instead of a free search? so that if someone searches in one language, the name appears in the search box in the form we have selected?

**Comment by katiihnat** [comment]
This is an example: http://csla.history.ox.ac.uk/search.php

**Comment by Kandroodi** [comment]
At the moment, it is possible to enter sains names in different languages. I didn't get the problem.
