### ISSUE TITLE
Location categories

### ISSUE THREAD

**Issue by Kandroodi** [Kandroodi/IberianSaints#33]
1- rename the original location to the institution
2- add a location field, exact location with a name (it can be a city or ...)
3- add region as a location. Each region has a name.

**Comment by katiihnat** [comment]
Hi Mojtaba,

Have you managed to add new location fields? we've been trying to enter data and we can't add cities yet. Do let me know if this is unclear!

Kati

**Comment by Kandroodi** [comment]
It is done.
