### ISSUE TITLE
Liturgical Manuscripts

### ISSUE THREAD

**Issue by katiihnat** [Kandroodi/IberianSaints#7]
Hi Mojtaba,

I think this goes for every object, church, inscription etc. 

We need to be able to add multiple saints for each of these - so every liturgical manuscript, object, church and inscription can have more than one saint. Is there a possibility to have more than one attached to these? I can't figure it out with the saint box at the bottom.

Thanks!

**Comment by katiihnat** [comment]
Forget that! I realized you have to hit 'Save' and then you can add another saint - it's all good!

**Comment by katiihnat** [comment]
Ok - I got an error message when trying to add a new saint:


Request Method: | POST
-- | --
http://127.0.0.1:6758/saint/new/
2.2
ValueError
invalid literal for int() with base 10: 'November'
/var/www/iberiansaints/live/venv-python3/lib/python3.5/site-packages/partial_date/partial_date.py in determine_type, line 96
/var/www/iberiansaints/live/venv-python3/bin/python
3.5.2
['/var/www/iberiansaints/live/repo',  '/var/www/iberiansaints/live/venv-python3/lib/python35.zip',  '/var/www/iberiansaints/live/venv-python3/lib/python3.5',  '/var/www/iberiansaints/live/venv-python3/lib/python3.5/plat-x86_64-linux-gnu',  '/var/www/iberiansaints/live/venv-python3/lib/python3.5/lib-dynload',  '/usr/lib/python3.5',  '/usr/lib/python3.5/plat-x86_64-linux-gnu',  '/var/www/iberiansaints/live/venv-python3/lib/python3.5/site-packages']

**Comment by katiihnat** [comment]
Oh I seem to have solved that - but I seem to receive an error message when I try to introduce a range of dates in 'date' of liturgical manuscript - so, 700-734 doesn't work. 

Is there a way to have a range of dates?

**Comment by Kandroodi** [comment]
For the Date fields you need to use the following format for different precisions:

Day: yyyy-mm-dd                   e.g. 1999-12-04  
Month: yyyy-mm                    e.g. 1999-12
Year: <integer>y                     e.g. 1999y
Decade: <integer>d               e.g.  200d       means 1990-2000
Century: <integer>c               e.g.  20c         means 1900-2000
Millennium: <integer>m        e.g.  2m          meand 1000-2000


If it is not sufficient, we can use two fields for each date field. Then, it is possible to enter a lower and upper bound for a date.

**Comment by Kandroodi** [comment]
The "range of date" issue is solved in issue #9 , using the lower and the upper bound for each date.
